# -*- coding: utf-8 -*-
"""
Created on Mon Feb  1 14:16:33 2021

@author: USER
"""

from mcpi.minecraft import Minecraft
import time
mc=Minecraft.create()
time.sleep(5)
x=1000
y=100
z=1000
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)
time.sleep(0.5)
y=y+1
mc.player.setPos(x,y,z)